### ISSUE TITLE
Testing multiple renderers

### ISSUE THREAD

**Issue by esonnino** [RandomFractals/vscode-data-table#148] opened 2023-02-21 21:34 UTC
Type: <b>Bug</b>

Auto-generated text from notebook cell performance. The duration for the renderer, Data Table, is slower than expected.
Execution Time: 174ms
Renderer Duration: 83ms

Extension version: 1.12.0
VS Code version: Code - Insiders 1.76.0-insider (5454665328aa30aeb989abfc195e7a7aacd94edf, 2023-02-21T05:22:58.320Z)
OS version: Windows_NT x64 10.0.22623
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-11370H @ 3.30GHz (8 x 3302)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.84GB (12.90GB free)|
|Process Argv|--crash-reporter-id 196a4020-90b2-430b-bc69-8e665a1a8055|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256197
vslsvsres303:30308271
pythonvspyl392:30422396
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30404738
cppdebug:30492333
vscaac:30438845
vsclangdf:30492506
c4g48928:30535728
dsvsc012:30540252
pynewext54:30618038
pylantcb52:30590116
pyindex848:30611229
nodejswelcome1:30587009
pyind779:30611226
pythonsymbol12:30651887
a9j8j154:30646983
showlangstatbar:30659908
pythonb192cf:30661257

```

</details>

**Comment by RandomFractals** [comment] 2023-02-21 22:04
@esonnino I am not sure what your A/B Experiments are showing.

The main metrics you have listed sound more like what rendering should take, which I believe is reasonably fast rendering performance:

>Execution Time: 174ms
>Renderer Duration: 83ms

Also, the actual rendering time will depend on the amount of data you are outputting from the notebook cell.

This is definitely not a bug, and I am going to close this ticket as invalid.

**Closed as completed by RandomFractals** 2023-02-21 22:04 UTC
Labels: invalid, wontfix
