### ISSUE TITLE
Can you please add Azure Data Studio Notebooks support? 

### ISSUE THREAD

**Issue by sudhagart** [RandomFractals/vscode-data-table#125] opened 2022-04-12 23:54 UTC
Azure Data Studio uses the same general framework as VS Code. But I suspect their notebook implementation is slightly different and extensions do not automatically carry over from VSCode marketplace to Azure Data Studio marketplace. .

**Comment by RandomFractals** [comment] 2022-04-13 13:37
@sudhagart Can you provide a link to the Azure Data Studio notebook examples?

I currently have Kusto notebooks support on my todo list: https://github.com/RandomFractals/vscode-data-table/issues/106

Is there more to it?

**Comment by sudhagart** [comment] 2022-04-13 16:45
Here is a pointer to the docs. https://docs.microsoft.com/en-us/sql/azure-data-studio/notebooks/notebooks-guidance?view=sql-server-ver15 

Azure Data Studio is just UX like VSCode - underneath it hosts python or various other kernels. So same notebooks can be run in VSCode \ Azure Data Studio or directly via Jupyter if it is based on the python kernel.  Azure Data Studio brings along other goodness that is DB specific. 

I know that Azure Data Studio has a Kusto plugin to enable Kusto notebooks. I am not sure if VSCode has support for Kusto notebooks as well, if it does - that may be just the Kusto kernel for the notebook infrastructure in VSCode.

**Comment by RandomFractals** [comment] 2022-07-23 22:20
closing this as duplicate of #106

**Closed as completed** 2022-07-23 22:20 UTC
Labels: duplicate
